// @generated drizzle-zero signature:sha256:4b50059692db271837f5a01b388121e1c47f1f1fe8f6baabb4c4a0d89377a13f
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { ReadonlyJSONValue, Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";
import type { CustomType } from "drizzle-zero";
import type * as drizzleSchema from "./schema/index";

const apiKeysTable = {
    "name": "apiKeys",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "userId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "keyHash": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "key_hash"
        },
        "keyPrefix": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "key_prefix"
        },
        "lastUsedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "last_used_at"
        },
        "expiresAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "expires_at"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "api_keys"
} as const;
const automationsTable = {
    "name": "automations",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "projectId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "project_id"
        },
        "repoConnectionId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "repo_connection_id"
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "enabled": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean
        },
        "cronExpression": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "cron_expression"
        },
        "taskTemplateTitle": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "task_template_title"
        },
        "taskTemplatePrompt": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "task_template_prompt"
        },
        "sandboxSize": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "small" | "medium" | "large",
            "serverName": "sandbox_size"
        },
        "permissionMode": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "custom" | "yolo" | "safe",
            "serverName": "permission_mode"
        },
        "branchPrefix": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "branch_prefix"
        },
        "policy": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as CustomType<typeof drizzleSchema, "automations", "policy">
        },
        "config": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as CustomType<typeof drizzleSchema, "automations", "config">
        },
        "metadata": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as CustomType<typeof drizzleSchema, "automations", "metadata">
        },
        "lastRunAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "last_run_at"
        },
        "nextRunAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "next_run_at"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const credentialsTable = {
    "name": "credentials",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "userId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "provider": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "source": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "encryptedAccessToken": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "encrypted_access_token"
        },
        "encryptedRefreshToken": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "encrypted_refresh_token"
        },
        "encryptedApiKey": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "encrypted_api_key"
        },
        "tokenExpiresAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "token_expires_at"
        },
        "profileEmail": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "profile_email"
        },
        "profileName": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "profile_name"
        },
        "subscriptionType": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "subscription_type"
        },
        "metadata": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as ReadonlyJSONValue
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const projectsTable = {
    "name": "projects",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "slug": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "description": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "defaultBranch": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "default_branch"
        },
        "rootDirectory": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "root_directory"
        },
        "metadata": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as CustomType<typeof drizzleSchema, "projects", "metadata">
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const repoConnectionsTable = {
    "name": "repoConnections",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "projectId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "project_id"
        },
        "provider": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "github"
        },
        "owner": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "repo": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "defaultBranch": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "default_branch"
        },
        "authType": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as CustomType<typeof drizzleSchema, "repoConnections", "authType">,
            "serverName": "auth_type"
        },
        "connectionMetadata": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as CustomType<typeof drizzleSchema, "repoConnections", "connectionMetadata">,
            "serverName": "connection_metadata"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "repo_connections"
} as const;
const runEventsTable = {
    "name": "runEvents",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "runId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "run_id"
        },
        "sequence": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number
        },
        "eventType": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as CustomType<typeof drizzleSchema, "runEvents", "eventType">,
            "serverName": "event_type"
        },
        "level": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "message": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "payload": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as CustomType<typeof drizzleSchema, "runEvents", "payload">
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "run_events"
} as const;
const runsTable = {
    "name": "runs",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "taskId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "task_id"
        },
        "repoConnectionId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "repo_connection_id"
        },
        "status": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "queued" | "running" | "completed" | "failed" | "cancelled" | "provisioning" | "cloning" | "paused"
        },
        "attempt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "prompt": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "baseBranch": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "base_branch"
        },
        "branchName": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "branch_name"
        },
        "sandboxSize": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as "small" | "medium" | "large",
            "serverName": "sandbox_size"
        },
        "permissionMode": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as "custom" | "yolo" | "safe",
            "serverName": "permission_mode"
        },
        "policy": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as CustomType<typeof drizzleSchema, "runs", "policy">
        },
        "config": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as CustomType<typeof drizzleSchema, "runs", "config">
        },
        "metadata": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as CustomType<typeof drizzleSchema, "runs", "metadata">
        },
        "startedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "started_at"
        },
        "completedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "completed_at"
        },
        "failedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "failed_at"
        },
        "errorMessage": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "error_message"
        },
        "workspacePath": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "workspace_path"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const sessionsTable = {
    "name": "sessions",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "userId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "token": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "expiresAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "expires_at"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const systemStatusTable = {
    "name": "systemStatus",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "service": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "status": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "checkedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "checked_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "system_status"
} as const;
const tasksTable = {
    "name": "tasks",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "projectId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "project_id"
        },
        "repoConnectionId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "repo_connection_id"
        },
        "automationId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "automation_id"
        },
        "title": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "prompt": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "status": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "pending" | "queued" | "running" | "completed" | "failed" | "cancelled"
        },
        "sandboxSize": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "small" | "medium" | "large",
            "serverName": "sandbox_size"
        },
        "permissionMode": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "custom" | "yolo" | "safe",
            "serverName": "permission_mode"
        },
        "baseBranch": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "base_branch"
        },
        "branchName": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "branch_name"
        },
        "policy": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as CustomType<typeof drizzleSchema, "tasks", "policy">
        },
        "config": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as CustomType<typeof drizzleSchema, "tasks", "config">
        },
        "metadata": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as CustomType<typeof drizzleSchema, "tasks", "metadata">
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const usersTable = {
    "name": "users",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "email": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "name": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "avatarUrl": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "avatar_url"
        },
        "authProvider": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "auth_provider"
        },
        "authProviderId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "auth_provider_id"
        },
        "passwordHash": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "password_hash"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const workspacesTable = {
    "name": "workspaces",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "ownerId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "owner_id"
        },
        "slug": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "description": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "metadata": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as CustomType<typeof drizzleSchema, "workspaces", "metadata">
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const apiKeysRelationships = {
    "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "users", "cardinality": "one" }]
} as const;
const automationsRelationships = {
    "workspace": [{ "sourceField": ["workspaceId"], "destField": ["id"], "destSchema": "workspaces", "cardinality": "one" }],
    "project": [{ "sourceField": ["projectId"], "destField": ["id"], "destSchema": "projects", "cardinality": "one" }],
    "repoConnection": [{ "sourceField": ["repoConnectionId"], "destField": ["id"], "destSchema": "repoConnections", "cardinality": "one" }],
    "tasks": [{ "sourceField": ["id"], "destField": ["automationId"], "destSchema": "tasks", "cardinality": "many" }]
} as const;
const credentialsRelationships = {
    "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "users", "cardinality": "one" }]
} as const;
const projectsRelationships = {
    "workspace": [{ "sourceField": ["workspaceId"], "destField": ["id"], "destSchema": "workspaces", "cardinality": "one" }],
    "repoConnections": [{ "sourceField": ["id"], "destField": ["projectId"], "destSchema": "repoConnections", "cardinality": "many" }],
    "tasks": [{ "sourceField": ["id"], "destField": ["projectId"], "destSchema": "tasks", "cardinality": "many" }],
    "automations": [{ "sourceField": ["id"], "destField": ["projectId"], "destSchema": "automations", "cardinality": "many" }]
} as const;
const repoConnectionsRelationships = {
    "workspace": [{ "sourceField": ["workspaceId"], "destField": ["id"], "destSchema": "workspaces", "cardinality": "one" }],
    "project": [{ "sourceField": ["projectId"], "destField": ["id"], "destSchema": "projects", "cardinality": "one" }],
    "tasks": [{ "sourceField": ["id"], "destField": ["repoConnectionId"], "destSchema": "tasks", "cardinality": "many" }],
    "runs": [{ "sourceField": ["id"], "destField": ["repoConnectionId"], "destSchema": "runs", "cardinality": "many" }],
    "automations": [{ "sourceField": ["id"], "destField": ["repoConnectionId"], "destSchema": "automations", "cardinality": "many" }]
} as const;
const runEventsRelationships = {
    "run": [{ "sourceField": ["runId"], "destField": ["id"], "destSchema": "runs", "cardinality": "one" }]
} as const;
const runsRelationships = {
    "task": [{ "sourceField": ["taskId"], "destField": ["id"], "destSchema": "tasks", "cardinality": "one" }],
    "repoConnection": [{ "sourceField": ["repoConnectionId"], "destField": ["id"], "destSchema": "repoConnections", "cardinality": "one" }],
    "events": [{ "sourceField": ["id"], "destField": ["runId"], "destSchema": "runEvents", "cardinality": "many" }]
} as const;
const sessionsRelationships = {
    "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "users", "cardinality": "one" }]
} as const;
const tasksRelationships = {
    "workspace": [{ "sourceField": ["workspaceId"], "destField": ["id"], "destSchema": "workspaces", "cardinality": "one" }],
    "project": [{ "sourceField": ["projectId"], "destField": ["id"], "destSchema": "projects", "cardinality": "one" }],
    "repoConnection": [{ "sourceField": ["repoConnectionId"], "destField": ["id"], "destSchema": "repoConnections", "cardinality": "one" }],
    "automation": [{ "sourceField": ["automationId"], "destField": ["id"], "destSchema": "automations", "cardinality": "one" }],
    "runs": [{ "sourceField": ["id"], "destField": ["taskId"], "destSchema": "runs", "cardinality": "many" }]
} as const;
const usersRelationships = {
    "apiKeys": [{ "sourceField": ["id"], "destField": ["userId"], "destSchema": "apiKeys", "cardinality": "many" }],
    "credentials": [{ "sourceField": ["id"], "destField": ["userId"], "destSchema": "credentials", "cardinality": "many" }],
    "sessions": [{ "sourceField": ["id"], "destField": ["userId"], "destSchema": "sessions", "cardinality": "many" }],
    "workspaces": [{ "sourceField": ["id"], "destField": ["ownerId"], "destSchema": "workspaces", "cardinality": "many" }]
} as const;
const workspacesRelationships = {
    "owner": [{ "sourceField": ["ownerId"], "destField": ["id"], "destSchema": "users", "cardinality": "one" }],
    "automations": [{ "sourceField": ["id"], "destField": ["workspaceId"], "destSchema": "automations", "cardinality": "many" }],
    "projects": [{ "sourceField": ["id"], "destField": ["workspaceId"], "destSchema": "projects", "cardinality": "many" }],
    "repoConnections": [{ "sourceField": ["id"], "destField": ["workspaceId"], "destSchema": "repoConnections", "cardinality": "many" }],
    "tasks": [{ "sourceField": ["id"], "destField": ["workspaceId"], "destSchema": "tasks", "cardinality": "many" }]
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
    "tables": {
        "apiKeys": apiKeysTable,
        "automations": automationsTable,
        "credentials": credentialsTable,
        "projects": projectsTable,
        "repoConnections": repoConnectionsTable,
        "runEvents": runEventsTable,
        "runs": runsTable,
        "sessions": sessionsTable,
        "systemStatus": systemStatusTable,
        "tasks": tasksTable,
        "users": usersTable,
        "workspaces": workspacesTable
    },
    "relationships": {
        "apiKeys": apiKeysRelationships,
        "automations": automationsRelationships,
        "credentials": credentialsRelationships,
        "projects": projectsRelationships,
        "repoConnections": repoConnectionsRelationships,
        "runEvents": runEventsRelationships,
        "runs": runsRelationships,
        "sessions": sessionsRelationships,
        "tasks": tasksRelationships,
        "users": usersRelationships,
        "workspaces": workspacesRelationships
    },
    "enableLegacyQueries": false,
    "enableLegacyMutators": false
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "apiKeys" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ApiKey = Row<(typeof schema)["tables"]["apiKeys"]>;
/**
 * Represents a row from the "automations" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Automation = Row<(typeof schema)["tables"]["automations"]>;
/**
 * Represents a row from the "credentials" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Credential = Row<(typeof schema)["tables"]["credentials"]>;
/**
 * Represents a row from the "projects" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Project = Row<(typeof schema)["tables"]["projects"]>;
/**
 * Represents a row from the "repoConnections" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RepoConnection = Row<(typeof schema)["tables"]["repoConnections"]>;
/**
 * Represents a row from the "runEvents" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RunEvent = Row<(typeof schema)["tables"]["runEvents"]>;
/**
 * Represents a row from the "runs" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Run = Row<(typeof schema)["tables"]["runs"]>;
/**
 * Represents a row from the "sessions" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Session = Row<(typeof schema)["tables"]["sessions"]>;
/**
 * Represents a row from the "systemStatus" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type SystemStatus = Row<(typeof schema)["tables"]["systemStatus"]>;
/**
 * Represents a row from the "tasks" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Task = Row<(typeof schema)["tables"]["tasks"]>;
/**
 * Represents a row from the "users" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)["tables"]["users"]>;
/**
 * Represents a row from the "workspaces" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Workspace = Row<(typeof schema)["tables"]["workspaces"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module '@rocicorp/zero' { interface DefaultTypes { schema: Schema; } }
